### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ole-is-live** [Saamstep/modmail#39]
```
(node:2356) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at hasCategory (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\index.js:766:13)
    at CommandoClient.<anonymous> (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\index.js:907:9)
    at CommandoClient.emit (events.js:327:22)
    at MessageCreateAction.handle (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\olebo\OneDrive\Dokumente\GitHub\FormelS\discord\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
 ```
    This error is spammed in the console
    It's about this line:
    
 ```
   // check if guild modmail category exists
function hasCategory(g) {
  if (g.channels.cache.find((ch) => ch.id == client.config.modmail.category || ch.name == client.config.modmail.category)) {
    return true;
  } else {
    return false;
  }
}

```

**Comment by Ole-is-live** [comment]
NPM: 7.5.6
NodeJS version: v12.18.0

**Comment by Saamstep** [comment]
Please assure sure your guild ID is set correctly in the `config.json` file

**Comment by Ole-is-live** [comment]
Oh thank you, I forgot to fill in ...
