### ISSUE TITLE
[BUG] - Issue with DM bot.

### ISSUE THREAD

**Issue by MikkelDK** [Saamstep/modmail#44]
**Describe the bug**
Writes DM to BOT and this error appears in PuTTY.

**To Reproduce**
1. Start the bot
2. DM the bot and type: hi
3. get an error about 'id'

**Console/Error logs**
```bash
(node:910395) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at CommandoClient.<anonymous> (/home/marc/modmail/index.js:449:112)
    at CommandoClient.emit (events.js:387:35)
    at MessageCreateAction.handle (/home/marc/modmail/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/marc/modmail/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/marc/modmail/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/marc/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/marc/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/marc/modmail/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (/home/marc/modmail/node_modules/ws/lib/websocket.js:970:20)
```

**System Info**
> Operating System/Host info: ``Ubuntu 20.04``
> NodeJS version: ``14.17.3`` 
> NPM version: ``6.14.13``
> DiscordJS version: ``12.5.3``
> Bot version: ``2.1.2``

**Comment by Saamstep** [comment]
Did you set a mod role in the config?
